name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

      - name: Check Environment Variables
        run: |
          echo "ANDROIDAPI: $ANDROIDAPI"
          echo "ANDROIDMINAPI: $ANDROIDMINAPI"
          echo "SDK Directory: $ANDROID_SDK_ROOT"
          echo "NDK Directory: $ANDROID_NDK_HOME"
        env:
          ANDROIDAPI: ${{ secrets.ANDROIDAPI }}
          ANDROIDMINAPI: ${{ secrets.ANDROIDMINAPI }}
          ANDROID_SDK_ROOT: ${{ secrets.ANDROID_SDK_ROOT }}
          ANDROID_NDK_HOME: ${{ secrets.ANDROID_NDK_HOME }}
